<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'OAuth2\\HttpFoundationBridge' => array($vendorDir . '/bshaffer/oauth2-server-httpfoundation-bridge/src'),
    'OAuth2' => array($vendorDir . '/bshaffer/oauth2-server-php/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Barryvdh' => array($vendorDir . '/barryvdh/reflection-docblock/src'),
);
